### ISSUE TITLE
Support Mac notifications natively

### ISSUE THREAD

**Issue by gbhrdt** [wokier/java-to-OS-notify#7]
Hello, very nice library, thank you! I've got one question: Wouldn't it be possible to support Mac notifications natively in any way, e.g. by bundling terminal-notifier in my application?

This one might be helpful as well: http://stackoverflow.com/questions/11712535/mac-mountain-lion-send-notification-from-cli-app/14698543#14698543

**Comment by wokier** [comment]
Hi

I am not sure to understand.
https://github.com/norio-nomura/usernotification shows how to send (i would say force to send) native notifications from an xproject , coded in Objective-C, that may be called from the command line using xcode.
xcode is a requirement for usernotification.
java-to-OS-notify allows to send native notifications from java code, using terminal-notifier.
So terminal-notifier is a requirement for java-to-OS-notify.
You may dont want your users to install temrinal-notifier. right?
But i don't understand the link between the java code and the packaged application.
Anyway, we can imagine to configure java-to-OS-notify to use a terminal-notifier alternative, that respect the same api, even copying its code, as soon as you respect its MIT licence https://github.com/alloy/terminal-notifier#license
But if your scope is limited to mac, and you know which application/command to call for notifications, java-to-OS-notify has no more added value in this case.

Please tell me if i miss something.

**Comment by gbhrdt** [comment]
Hi,
you're right, I just don't want that my users have to install anything. The provided link was probably wrong then, sorry.
My question was if it is possible to bundle terminal-notifier in any way to my java project?

**Comment by wokier** [comment]
Hi
terminal-notifier needs to be installed for native notifications.
You cannot 'bundle' it into a java application. 
Growl is an alternative, but also needs an installation.
Java system tray is the only option which does not need any installation.
java-to-OS-notify will use the better available notification system.
